#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 5b: Prototype Hylleraas/R12 correction diagnostics for He.

Purpose
-------
This script is a controlled prototype, not the final literature-level [2]R12
implementation.

It reads Step-5a intermediates and evaluates several pair-space correction
diagnostics using the Q-projected F12 amplitudes:

    A_raw_Q = Q f12 |Psi_0>
    A_sp_Q  = Q f12(SP) |Psi_0>

The script computes:

1. Fixed-amplitude Hylleraas diagnostic:
       J[A] = <A|(H - E0)|A> + 2 <Psi0|H|A>

2. Scalar-optimized one-vector correction:
       min_lambda J[lambda A]
       lambda* = - <Psi0|H|A> / <A|(H-E0)|A>
       DeltaE_1D = - coupling^2 / quadratic

3. Full Q-pair solve diagnostic:
       DeltaE_Q = - b^T (H_QQ - E0)^(-1) b
       b = H_QP Psi0

This third quantity is an ordinary pair-space external correction in the RI
space.  It is included only as a reference diagnostic.  It is not the [2]R12
correction.

Why this step?
--------------
Before coding the full [2]R12 contraction, we need to verify signs, Q-space
projection, pair-Hamiltonian convention, coupling vectors, and the numerical
behavior of the F12-generated first-order amplitudes.

Input
-----
Default:
    he_ccpvdz_step5a_r12_intermediates.npz

Generated by:
    step5a_he_r12_intermediate_check.py

Usage
-----
    python step5b_he_r12_prototype_correction.py

Optional:
    python step5b_he_r12_prototype_correction.py --inp he_ccpvdz_step5a_r12_intermediates.npz
    python step5b_he_r12_prototype_correction.py --eig-thresh 1e-10
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Dict, Any, Tuple

import numpy as np


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--inp", default="he_ccpvdz_step5a_r12_intermediates.npz")
    p.add_argument("--out", default="he_ccpvdz_step5b_r12_prototype_correction.npz")
    p.add_argument("--summary", default="he_ccpvdz_step5b_r12_prototype_correction_summary.txt")
    p.add_argument("--eig-thresh", type=float, default=1e-10)
    p.add_argument("--max-pair-dim", type=int, default=5000)
    return p.parse_args()


def maxabs(A: np.ndarray) -> float:
    return float(np.max(np.abs(A))) if A.size else 0.0


def sym(A: np.ndarray) -> np.ndarray:
    return 0.5 * (A + A.T)


def load_metadata(data) -> Dict[str, Any]:
    if "metadata_json" not in data:
        return {}
    try:
        return json.loads(str(data["metadata_json"]))
    except Exception:
        return {}


def build_pair_hamiltonian(h: np.ndarray, eri: np.ndarray) -> np.ndarray:
    """
    Ordered alpha-beta pair basis |p alpha, q beta>.

    <p_a q_b | H | r_a s_b>
      = h[p,r] delta[q,s] + h[q,s] delta[p,r] + (p r | q s)

    eri[p,q,r,s] = (pq|rs).
    """
    n = h.shape[0]
    H = np.zeros((n * n, n * n), dtype=float)
    for p in range(n):
        for q in range(n):
            I = p * n + q
            for r in range(n):
                for s in range(n):
                    J = r * n + s
                    val = 0.0
                    if q == s:
                        val += h[p, r]
                    if p == r:
                        val += h[q, s]
                    val += eri[p, r, q, s]
                    H[I, J] = val
    return sym(H)


def q_indices(nri: int, nobs: int) -> np.ndarray:
    idx = []
    for p in range(nri):
        for q in range(nri):
            if not (p < nobs and q < nobs):
                idx.append(p * nri + q)
    return np.array(idx, dtype=int)


def pp_indices(nri: int, nobs: int) -> np.ndarray:
    idx = []
    for p in range(nobs):
        for q in range(nobs):
            idx.append(p * nri + q)
    return np.array(idx, dtype=int)


def pair_block_norms_from_vec(v: np.ndarray, nri: int, nobs: int) -> Dict[str, float]:
    A = v.reshape(nri, nri)
    P = slice(0, nobs)
    C = slice(nobs, nri)
    return {
        "PP": float(np.linalg.norm(A[P, P])),
        "PC": float(np.linalg.norm(A[P, C])),
        "CP": float(np.linalg.norm(A[C, P])),
        "CC": float(np.linalg.norm(A[C, C])),
        "Q": float(np.linalg.norm(A.copy().reshape(nri, nri)[np.logical_not(np.outer(np.arange(nri) < nobs, np.arange(nri) < nobs))])),
        "total": float(np.linalg.norm(A)),
    }


def one_vector_hylleraas(H: np.ndarray, psi0: np.ndarray, Avec: np.ndarray, E0: float, eig_thresh: float) -> Dict[str, Any]:
    """
    J(lambda A) = lambda^2 q + 2 lambda c.
    q = A^T (H-E0) A
    c = psi0^T H A

    If q > 0, optimum correction is -c^2/q.
    """
    H0 = H - E0 * np.eye(H.shape[0])
    norm_A = float(np.linalg.norm(Avec))
    norm_psi = float(np.linalg.norm(psi0))

    q = float(Avec @ (H0 @ Avec))
    c = float(psi0 @ (H @ Avec))
    fixed_J = q + 2.0 * c

    if abs(q) > eig_thresh:
        lam = -c / q
        delta_1d = -c * c / q
        scaled_norm = abs(lam) * norm_A
    else:
        lam = None
        delta_1d = None
        scaled_norm = None

    overlap_with_psi0 = float(psi0 @ Avec)
    return {
        "norm_A": norm_A,
        "norm_psi0": norm_psi,
        "overlap_psi0_A": overlap_with_psi0,
        "quadratic_A_HminusE_A": q,
        "coupling_psi0_H_A": c,
        "fixed_amplitude_J": fixed_J,
        "lambda_opt": lam,
        "deltaE_1D_opt": delta_1d,
        "scaled_norm_at_lambda_opt": scaled_norm,
        "q_positive": bool(q > eig_thresh),
    }


def full_q_solve(H: np.ndarray, psi0: np.ndarray, qidx: np.ndarray, E0: float, eig_thresh: float) -> Dict[str, Any]:
    """
    Q-space Hylleraas solve:
        A = H_QQ - E0 I
        b = H_QP psi0
        Delta = - b^T A^{-1} b

    This is an ordinary external pair-space diagnostic.
    """
    HQQ = H[np.ix_(qidx, qidx)]
    H0QQ = sym(HQQ - E0 * np.eye(len(qidx)))
    b = H[np.ix_(qidx, np.arange(H.shape[0]))] @ psi0

    evals, U = np.linalg.eigh(H0QQ)
    min_eval = float(np.min(evals)) if evals.size else np.nan
    max_eval = float(np.max(evals)) if evals.size else np.nan
    n_nonpos = int(np.sum(evals <= eig_thresh))
    cond_pos = None
    if np.all(evals > eig_thresh):
        cond_pos = float(max_eval / min_eval)
        x = np.linalg.solve(H0QQ, b)
        method = "solve"
    else:
        inv_evals = np.zeros_like(evals)
        keep = np.abs(evals) > eig_thresh
        inv_evals[keep] = 1.0 / evals[keep]
        x = U @ (inv_evals * (U.T @ b))
        method = "eigen_pseudoinverse_signed"

    delta = -float(b @ x)
    residual = float(np.linalg.norm(H0QQ @ x - b))
    norm_b = float(np.linalg.norm(b))
    norm_x = float(np.linalg.norm(x))

    # Diagonal EN-like comparison.
    diag = np.diag(H0QQ)
    valid = np.abs(diag) > eig_thresh
    delta_diag = -float(np.sum((b[valid] ** 2) / diag[valid]))
    n_bad_diag = int(np.sum(~valid))
    n_nonpos_diag = int(np.sum(diag <= eig_thresh))

    return {
        "q_dim": int(len(qidx)),
        "method": method,
        "deltaE_full_Q_pair_diagnostic": delta,
        "residual_norm": residual,
        "norm_b": norm_b,
        "norm_x": norm_x,
        "min_eig_HQQ_minus_E": min_eval,
        "max_eig_HQQ_minus_E": max_eval,
        "n_eig_le_thresh": n_nonpos,
        "condition_positive_subspace": cond_pos,
        "deltaE_diag_EN_like": delta_diag,
        "n_bad_diag": n_bad_diag,
        "n_diag_le_thresh": n_nonpos_diag,
        "eigenvalues_first10": evals[:10].tolist(),
        "eigenvalues_last10": evals[-10:].tolist(),
        "x_solution": x,
        "b_vector": b,
    }


def vector_alignment(a: np.ndarray, b: np.ndarray) -> Dict[str, float]:
    na = float(np.linalg.norm(a))
    nb = float(np.linalg.norm(b))
    if na == 0.0 or nb == 0.0:
        cos = None
    else:
        cos = float((a @ b) / (na * nb))
    return {
        "norm_a": na,
        "norm_b": nb,
        "dot": float(a @ b),
        "cosine": cos,
    }


def main():
    args = parse_args()

    print("=" * 80)
    print("Step 5b | Prototype R12/Hylleraas correction diagnostics | He")
    print("=" * 80)
    print(f"input = {args.inp}")

    data = np.load(args.inp, allow_pickle=True)
    meta = load_metadata(data)

    required = ["h_ri", "eri_ri", "Cab_obs", "A_raw_Q", "A_sp_Q", "metadata_json"]
    missing = [k for k in required if k not in data]
    if missing:
        raise RuntimeError(f"Missing required arrays in {args.inp}: {missing}")

    h_ri = np.array(data["h_ri"], dtype=float)
    eri_ri = np.array(data["eri_ri"], dtype=float)
    Cab_obs = np.array(data["Cab_obs"], dtype=float)
    A_raw_Q = np.array(data["A_raw_Q"], dtype=float)
    A_sp_Q = np.array(data["A_sp_Q"], dtype=float)

    nobs = int(meta.get("nobs", Cab_obs.shape[0]))
    nri = h_ri.shape[0]
    ncabs = nri - nobs
    E_ref_elec = float(meta["E_ref_elec"])
    E_obs_fci = float(meta["E_obs_fci"])
    enuc = float(meta.get("enuc", E_obs_fci - E_ref_elec))

    pair_dim = nri * nri
    if pair_dim > args.max_pair_dim:
        raise RuntimeError(f"pair_dim={pair_dim} exceeds --max-pair-dim={args.max_pair_dim}")

    H = build_pair_hamiltonian(h_ri, eri_ri)
    qidx = q_indices(nri, nobs)
    pidx = pp_indices(nri, nobs)

    psi0 = np.zeros((nri, nri), dtype=float)
    psi0[:nobs, :nobs] = Cab_obs
    psi0_vec = psi0.reshape(-1)

    A_raw_vec = A_raw_Q.reshape(-1)
    A_sp_vec = A_sp_Q.reshape(-1)

    # Basic validation.
    E_pair_psi0 = float(psi0_vec @ H @ psi0_vec)
    norm_psi0 = float(np.linalg.norm(psi0_vec))
    overlap_raw = float(psi0_vec @ A_raw_vec)
    overlap_sp = float(psi0_vec @ A_sp_vec)

    print(f"nobs = {nobs}, ncabs = {ncabs}, nri = {nri}, pair_dim = {pair_dim}")
    print(f"E_ref_elec from metadata      = {E_ref_elec: .14f} Eh")
    print(f"E_pair(psi0)                 = {E_pair_psi0: .14f} Eh")
    print(f"Delta pair psi0 - E_ref_elec = {E_pair_psi0 - E_ref_elec: .3e} Eh")
    print(f"||psi0||                     = {norm_psi0:.12f}")
    print(f"<psi0|A_raw_Q>               = {overlap_raw:.3e}")
    print(f"<psi0|A_sp_Q>                = {overlap_sp:.3e}")

    raw_diag = one_vector_hylleraas(H, psi0_vec, A_raw_vec, E_ref_elec, args.eig_thresh)
    sp_diag = one_vector_hylleraas(H, psi0_vec, A_sp_vec, E_ref_elec, args.eig_thresh)

    qsolve = full_q_solve(H, psi0_vec, qidx, E_ref_elec, args.eig_thresh)
    # Embed Q solution to full pair vector for alignments.
    x_full = np.zeros(pair_dim, dtype=float)
    x_full[qidx] = qsolve["x_solution"]
    b_full = np.zeros(pair_dim, dtype=float)
    b_full[qidx] = qsolve["b_vector"]

    raw_align_x = vector_alignment(A_raw_vec, x_full)
    sp_align_x = vector_alignment(A_sp_vec, x_full)
    raw_align_b = vector_alignment(A_raw_vec, b_full)
    sp_align_b = vector_alignment(A_sp_vec, b_full)

    print("\n[One-vector Hylleraas diagnostics]")
    for name, d in [("A_raw_Q", raw_diag), ("A_sp_Q", sp_diag)]:
        print(f"{name}:")
        print(f"  ||A||                    = {d['norm_A']:.6e}")
        print(f"  q=<A|(H-E)|A>            = {d['quadratic_A_HminusE_A']: .8e}")
        print(f"  c=<psi0|H|A>             = {d['coupling_psi0_H_A']: .8e}")
        print(f"  J_fixed                  = {d['fixed_amplitude_J']: .8e}")
        print(f"  lambda_opt               = {d['lambda_opt']}")
        print(f"  DeltaE_1D_opt            = {d['deltaE_1D_opt']}")

    print("\n[Full Q-pair diagnostic: ordinary external-pair reference]")
    print(f"Q dimension                = {qsolve['q_dim']}")
    print(f"method                     = {qsolve['method']}")
    print(f"min eig(H_QQ-E)            = {qsolve['min_eig_HQQ_minus_E']:.8e}")
    print(f"max eig(H_QQ-E)            = {qsolve['max_eig_HQQ_minus_E']:.8e}")
    print(f"n eig <= thresh            = {qsolve['n_eig_le_thresh']}")
    print(f"DeltaE_full_Q_pair         = {qsolve['deltaE_full_Q_pair_diagnostic']: .8e}")
    print(f"DeltaE_diag_EN_like        = {qsolve['deltaE_diag_EN_like']: .8e}")
    print(f"residual norm              = {qsolve['residual_norm']:.6e}")

    print("\n[Alignment with full Q solution]")
    print(f"cos(A_raw_Q, x_Q)          = {raw_align_x['cosine']}")
    print(f"cos(A_sp_Q,  x_Q)          = {sp_align_x['cosine']}")
    print(f"cos(A_raw_Q, b_Q)          = {raw_align_b['cosine']}")
    print(f"cos(A_sp_Q,  b_Q)          = {sp_align_b['cosine']}")

    # Convert corrections to total energies for readability.
    def total_energy(delta):
        return None if delta is None else E_obs_fci + float(delta)

    energies = {
        "E_obs_fci": E_obs_fci,
        "E_raw_fixed": total_energy(raw_diag["fixed_amplitude_J"]),
        "E_raw_1D_opt": total_energy(raw_diag["deltaE_1D_opt"]),
        "E_sp_fixed": total_energy(sp_diag["fixed_amplitude_J"]),
        "E_sp_1D_opt": total_energy(sp_diag["deltaE_1D_opt"]),
        "E_full_Q_pair": total_energy(qsolve["deltaE_full_Q_pair_diagnostic"]),
        "E_diag_EN_like": total_energy(qsolve["deltaE_diag_EN_like"]),
    }

    print("\n[Prototype corrected total energies]")
    for k, v in energies.items():
        print(f"{k:<18s} = {v}")

    metadata = {
        "source_file": args.inp,
        "nobs": nobs,
        "ncabs": ncabs,
        "nri": nri,
        "pair_dim": pair_dim,
        "E_ref_elec": E_ref_elec,
        "E_obs_fci": E_obs_fci,
        "enuc": enuc,
        "E_pair_psi0": E_pair_psi0,
        "delta_pair_psi0_minus_E_ref_elec": float(E_pair_psi0 - E_ref_elec),
        "norm_psi0": norm_psi0,
        "overlap_psi0_A_raw_Q": overlap_raw,
        "overlap_psi0_A_sp_Q": overlap_sp,
        "pair_block_norms": {
            "A_raw_Q": pair_block_norms_from_vec(A_raw_vec, nri, nobs),
            "A_sp_Q": pair_block_norms_from_vec(A_sp_vec, nri, nobs),
            "x_full_Q_solution": pair_block_norms_from_vec(x_full, nri, nobs),
            "b_full_Q_coupling": pair_block_norms_from_vec(b_full, nri, nobs),
        },
        "one_vector": {
            "A_raw_Q": raw_diag,
            "A_sp_Q": sp_diag,
        },
        "full_Q_pair_diagnostic": {
            k: v for k, v in qsolve.items()
            if k not in ["x_solution", "b_vector"]
        },
        "alignment": {
            "A_raw_Q_vs_x_Q": raw_align_x,
            "A_sp_Q_vs_x_Q": sp_align_x,
            "A_raw_Q_vs_b_Q": raw_align_b,
            "A_sp_Q_vs_b_Q": sp_align_b,
        },
        "prototype_corrected_total_energies": energies,
        "important_note": (
            "These are prototype diagnostics, not the final article-level [2]R12 correction. "
            "A_raw_Q and A_sp_Q are generated using the current testing Gaussian factor. "
            "The full_Q_pair quantity is an ordinary external pair-space correction, included only as a reference."
        ),
    }

    np.savez(
        args.out,
        H_pair=H,
        qidx=qidx,
        pidx=pidx,
        psi0_pair=psi0,
        A_raw_Q=A_raw_Q,
        A_sp_Q=A_sp_Q,
        x_full_Q_solution=x_full.reshape(nri, nri),
        b_full_Q_coupling=b_full.reshape(nri, nri),
        h_ri=h_ri,
        eri_ri=eri_ri,
        metadata_json=np.array(json.dumps(metadata, indent=2)),
    )

    with open(args.summary, "w", encoding="utf-8") as f:
        f.write(json.dumps(metadata, indent=2))
        f.write("\n")

    print("\n[Saved]")
    print(" ", args.out)
    print(" ", args.summary)

    ok = (
        abs(E_pair_psi0 - E_ref_elec) < 1e-10
        and abs(norm_psi0 - 1.0) < 1e-10
        and abs(overlap_raw) < 1e-10
        and abs(overlap_sp) < 1e-10
        and np.isfinite(raw_diag["fixed_amplitude_J"])
        and np.isfinite(sp_diag["fixed_amplitude_J"])
        and np.isfinite(qsolve["deltaE_full_Q_pair_diagnostic"])
    )

    if not ok:
        print("\nERROR: Step 5b diagnostic consistency check failed.")
        print("Inspect pair-space energy, Q projection, and finite correction values.")
        sys.exit(2)

    print("\nStatus: Step 5b prototype correction diagnostics passed.")


if __name__ == "__main__":
    main()
