#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 2: CABS+ construction and orthogonality check for He.

This script is the second test layer for the ECG-NO + [2]R12 workflow.

Input
-----
A Step-1 npz reference file, e.g.

    he_631g_detci_rdm_ref.npz

generated by step1_psi4_he_detci_rdm_check_v2.py.

The file supplies C_obs in the OBS AO basis.  Here, for the GBS test,
C_obs is the Psi4 MO coefficient matrix from the OBS basis, e.g. He/6-31G.

Purpose
-------
Given:

    OBS basis  : e.g. 6-31G
    raw CABS   : e.g. cc-pVDZ

construct a CABS+ complementary space by:

1. building overlap matrices in the mixed basis OBS-AO ⊕ CABS-AO;
2. projecting raw CABS functions against the OBS orbital space;
3. orthonormalizing the projected CABS space;
4. verifying

       C_obs^T  S  C_obs   = I
       C_cabs^T S  C_cabs  = I
       C_obs^T  S  C_cabs  = 0

The output is a block-basis representation.  The block basis is

       [ OBS-AO functions ; raw CABS-AO functions ]

and the block overlap is

       S_block = [[S_obs, S_obs_cabs],
                  [S_cabs_obs, S_cabs]]

This representation is sufficient for checking CABS+ linear algebra and will
serve as the interface before adding F12 integral generation.

Usage
-----
    python step2_he_cabs_plus_check.py

Common options
--------------
    python step2_he_cabs_plus_check.py --obs-basis 6-31g --cabs-basis cc-pvdz
    python step2_he_cabs_plus_check.py --nobs 1
    python step2_he_cabs_plus_check.py --thresh 1e-10

Notes
-----
If OBS spans a basis that is identical to the raw CABS basis, projection removes
all raw CABS vectors.  Use a larger or different CABS basis, e.g. cc-pVDZ,
aug-cc-pVDZ, or a suitable F12/RI basis if available.
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Tuple, Dict, Any

import numpy as np


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--ref", default="he_631g_detci_rdm_ref.npz", help="Step-1 npz file.")
    p.add_argument("--obs-basis", default="6-31g", help="OBS basis name used in Step 1.")
    p.add_argument("--cabs-basis", default="cc-pvdz", help="Raw CABS basis name.")
    p.add_argument("--memory", default="2 GB", help="Psi4 memory.")
    p.add_argument("--nthreads", type=int, default=1, help="Psi4 threads.")
    p.add_argument("--nobs", type=int, default=None, help="Number of OBS orbitals to retain. Default: all MOs.")
    p.add_argument("--thresh", type=float, default=1e-10, help="Eigenvalue threshold for projected CABS overlap.")
    p.add_argument("--out", default=None, help="Output npz. Default depends on bases.")
    p.add_argument("--summary", default=None, help="Summary txt. Default depends on bases.")
    p.add_argument("--psi4-output", default=None, help="Psi4 output file.")
    return p.parse_args()


def safe_label(s: str) -> str:
    return s.lower().replace("*", "s").replace("+", "p").replace("-", "").replace("_", "")


def sym(A: np.ndarray) -> np.ndarray:
    return 0.5 * (A + A.T)


def maxabs(A: np.ndarray) -> float:
    return float(np.max(np.abs(A))) if A.size else 0.0


def asarray_psi4_matrix(x):
    return np.array(np.asarray(x), dtype=float, copy=True)


def build_psi4_basis_overlaps(obs_basis: str, cabs_basis: str, memory: str, nthreads: int, output_file: str):
    """
    Build S_obs, S_cabs, and S_obs_cabs with Psi4.

    S_obs_cabs has shape (nao_obs, nao_cabs) and entries <chi_obs_mu|chi_cabs_nu>.
    """
    try:
        import psi4
    except Exception as exc:
        raise RuntimeError("Cannot import psi4. Activate the Psi4 environment first.") from exc

    psi4.core.clean()
    psi4.set_memory(memory)
    psi4.set_num_threads(nthreads)
    psi4.core.set_output_file(output_file, False)

    mol = psi4.geometry(
        """
        0 1
        He 0.0 0.0 0.0
        symmetry c1
        units bohr
        """
    )

    # Build basis sets on the same molecule/center.
    # puream follows Psi4 defaults for these named bases.
    obs_bs = psi4.core.BasisSet.build(mol, "BASIS", obs_basis)
    cabs_bs = psi4.core.BasisSet.build(mol, "BASIS", cabs_basis)

    mints = psi4.core.MintsHelper(obs_bs)

    try:
        S_obs = asarray_psi4_matrix(mints.ao_overlap(obs_bs, obs_bs))
        S_cabs = asarray_psi4_matrix(mints.ao_overlap(cabs_bs, cabs_bs))
        S_obs_cabs = asarray_psi4_matrix(mints.ao_overlap(obs_bs, cabs_bs))
    except TypeError:
        # Some Psi4 builds expose only no-argument ao_overlap for the helper basis.
        # Cross-overlap should normally be available; if not, fail explicitly.
        raise RuntimeError(
            "This Psi4 build did not accept mints.ao_overlap(basis1, basis2). "
            "Cross overlaps are required for CABS+ construction."
        )

    return S_obs, S_cabs, S_obs_cabs, obs_bs.nbf(), cabs_bs.nbf()


def build_cabs_plus(C_obs: np.ndarray, S_obs: np.ndarray, S_cabs: np.ndarray, S_obs_cabs: np.ndarray,
                    thresh: float = 1e-10) -> Dict[str, Any]:
    """
    Construct CABS+ in the mixed block basis OBS-AO ⊕ raw-CABS-AO.

    C_obs is nao_obs x nobs and must be S_obs-orthonormal.

    Returns a dictionary with block overlap and coefficient matrices.
    """
    nao_obs, nobs = C_obs.shape
    nao_cabs = S_cabs.shape[0]

    if S_obs.shape != (nao_obs, nao_obs):
        raise ValueError(f"S_obs shape {S_obs.shape} incompatible with C_obs {C_obs.shape}")
    if S_obs_cabs.shape != (nao_obs, nao_cabs):
        raise ValueError(f"S_obs_cabs shape {S_obs_cabs.shape} incompatible")

    S_block = np.block(
        [
            [S_obs, S_obs_cabs],
            [S_obs_cabs.T, S_cabs],
        ]
    )

    C_obs_block = np.vstack([C_obs, np.zeros((nao_cabs, nobs))])
    B_raw_block = np.vstack([np.zeros((nao_obs, nao_cabs)), np.eye(nao_cabs)])

    # OBS should be orthonormal.
    obs_metric = C_obs_block.T @ S_block @ C_obs_block
    obs_orth_error = maxabs(obs_metric - np.eye(nobs))

    # Project raw CABS against OBS:
    # Q = B - C_obs (C_obs^T S B), valid because C_obs^T S C_obs = I.
    O = C_obs_block.T @ S_block @ B_raw_block
    Q = B_raw_block - C_obs_block @ O

    # Orthonormalize projected CABS under the block metric.
    S_Q = sym(Q.T @ S_block @ Q)
    evals, U = np.linalg.eigh(S_Q)
    idx = np.argsort(evals)[::-1]
    evals = evals[idx]
    U = U[:, idx]
    keep = evals > thresh

    if np.count_nonzero(keep) == 0:
        C_cabs_block = np.zeros((nao_obs + nao_cabs, 0))
    else:
        C_cabs_block = Q @ U[:, keep] @ np.diag(1.0 / np.sqrt(evals[keep]))

    C_ri_block = np.hstack([C_obs_block, C_cabs_block])

    cabs_metric = C_cabs_block.T @ S_block @ C_cabs_block
    cross_metric = C_obs_block.T @ S_block @ C_cabs_block
    ri_metric = C_ri_block.T @ S_block @ C_ri_block

    info = {
        "S_block": S_block,
        "C_obs_block": C_obs_block,
        "C_cabs_block": C_cabs_block,
        "C_ri_block": C_ri_block,
        "projected_cabs_overlap_evals": evals,
        "keep": keep,
        "obs_orth_error": float(obs_orth_error),
        "cabs_orth_error": maxabs(cabs_metric - np.eye(C_cabs_block.shape[1])) if C_cabs_block.shape[1] else 0.0,
        "obs_cabs_cross_error": maxabs(cross_metric),
        "ri_orth_error": maxabs(ri_metric - np.eye(C_ri_block.shape[1])),
        "nobs": int(nobs),
        "nao_obs": int(nao_obs),
        "nao_raw_cabs": int(nao_cabs),
        "ncabs": int(C_cabs_block.shape[1]),
        "nri": int(C_ri_block.shape[1]),
        "n_dropped": int(np.count_nonzero(~keep)),
        "min_kept_eval": float(np.min(evals[keep])) if np.any(keep) else None,
        "max_dropped_eval": float(np.max(evals[~keep])) if np.any(~keep) else None,
    }
    return info


def main():
    args = parse_args()

    obs_label = safe_label(args.obs_basis)
    cabs_label = safe_label(args.cabs_basis)
    if args.out is None:
        args.out = f"he_{obs_label}_obs_{cabs_label}_cabsplus.npz"
    if args.summary is None:
        args.summary = f"he_{obs_label}_obs_{cabs_label}_cabsplus_summary.txt"
    if args.psi4_output is None:
        args.psi4_output = f"psi4_he_{obs_label}_{cabs_label}_cabsplus.out"

    print("=" * 80)
    print("Step 2 | CABS+ construction check | He")
    print("=" * 80)
    print(f"Step-1 reference = {args.ref}")
    print(f"OBS basis        = {args.obs_basis}")
    print(f"raw CABS basis   = {args.cabs_basis}")
    print(f"threshold        = {args.thresh:.3e}")

    try:
        ref = np.load(args.ref, allow_pickle=True)
    except FileNotFoundError:
        raise FileNotFoundError(
            f"Cannot find {args.ref}. Run Step 1 first, e.g.\n"
            f"  python step1_psi4_he_detci_rdm_check_v2.py --basis {args.obs_basis}"
        )

    C_mo = np.array(ref["C_mo"], dtype=float, copy=True)
    S_obs_from_ref = np.array(ref["S_ao"], dtype=float, copy=True)

    S_obs, S_cabs, S_obs_cabs, nao_obs, nao_cabs = build_psi4_basis_overlaps(
        args.obs_basis,
        args.cabs_basis,
        args.memory,
        args.nthreads,
        args.psi4_output,
    )

    if C_mo.shape[0] != nao_obs:
        raise RuntimeError(
            f"C_mo from {args.ref} has {C_mo.shape[0]} AO rows, but Psi4 {args.obs_basis} has {nao_obs} basis functions. "
            f"Check --obs-basis and Step-1 reference file."
        )

    sdiff = maxabs(S_obs - S_obs_from_ref)
    if sdiff > 1e-8:
        print(f"WARNING: S_obs differs from Step-1 S_ao by {sdiff:.3e}. Check basis naming/order.")
    else:
        print(f"Max|S_obs(Psi4) - S_obs(Step1)| = {sdiff:.3e}")

    nmo = C_mo.shape[1]
    nobs = nmo if args.nobs is None else int(args.nobs)
    if nobs < 1 or nobs > nmo:
        raise ValueError(f"--nobs must be between 1 and {nmo}, got {nobs}")

    C_obs = C_mo[:, :nobs]
    result = build_cabs_plus(C_obs, S_obs, S_cabs, S_obs_cabs, thresh=args.thresh)

    evals = result["projected_cabs_overlap_evals"]
    keep = result["keep"]

    print("\n[Dimensions]")
    print(f"nao_obs       = {result['nao_obs']}")
    print(f"nobs          = {result['nobs']}")
    print(f"nao_raw_cabs  = {result['nao_raw_cabs']}")
    print(f"ncabs kept    = {result['ncabs']}")
    print(f"nri           = {result['nri']}")
    print(f"dropped       = {result['n_dropped']}")

    print("\n[Projected CABS overlap eigenvalues]")
    print("largest 10 =", np.array2string(evals[:10], precision=6, suppress_small=False))
    print("smallest 10 =", np.array2string(evals[-10:], precision=6, suppress_small=False))
    print(f"min kept eval    = {result['min_kept_eval']}")
    print(f"max dropped eval = {result['max_dropped_eval']}")

    print("\n[Orthogonality checks]")
    print(f"Max|C_obs^T S C_obs - I|       = {result['obs_orth_error']:.3e}")
    print(f"Max|C_cabs^T S C_cabs - I|     = {result['cabs_orth_error']:.3e}")
    print(f"Max|C_obs^T S C_cabs|          = {result['obs_cabs_cross_error']:.3e}")
    print(f"Max|C_ri^T S C_ri - I|         = {result['ri_orth_error']:.3e}")

    metadata = {
        "system": "He",
        "obs_basis": args.obs_basis,
        "cabs_basis": args.cabs_basis,
        "ref_file": args.ref,
        "threshold": args.thresh,
        "block_basis": "[OBS-AO ; raw-CABS-AO]",
        "nao_obs": result["nao_obs"],
        "nobs": result["nobs"],
        "nao_raw_cabs": result["nao_raw_cabs"],
        "ncabs": result["ncabs"],
        "nri": result["nri"],
        "n_dropped": result["n_dropped"],
        "obs_orth_error": result["obs_orth_error"],
        "cabs_orth_error": result["cabs_orth_error"],
        "obs_cabs_cross_error": result["obs_cabs_cross_error"],
        "ri_orth_error": result["ri_orth_error"],
        "min_kept_eval": result["min_kept_eval"],
        "max_dropped_eval": result["max_dropped_eval"],
        "S_obs_ref_diff": sdiff,
    }

    np.savez(
        args.out,
        S_obs=S_obs,
        S_cabs_raw=S_cabs,
        S_obs_cabs=S_obs_cabs,
        S_block=result["S_block"],
        C_obs_ao=C_obs,
        C_obs_block=result["C_obs_block"],
        C_cabs_block=result["C_cabs_block"],
        C_ri_block=result["C_ri_block"],
        projected_cabs_overlap_evals=evals,
        keep=keep,
        metadata_json=np.array(json.dumps(metadata, indent=2)),
    )

    with open(args.summary, "w", encoding="utf-8") as f:
        f.write(json.dumps(metadata, indent=2))
        f.write("\n\nProjected CABS overlap eigenvalues:\n")
        f.write(np.array2string(evals, precision=16, suppress_small=False))
        f.write("\n")

    print("\n[Saved]")
    print(" ", args.out)
    print(" ", args.summary)

    ok = (
        result["obs_orth_error"] < 1e-8
        and result["cabs_orth_error"] < 1e-8
        and result["obs_cabs_cross_error"] < 1e-8
        and result["ri_orth_error"] < 1e-8
        and result["ncabs"] > 0
    )

    if not ok:
        print("\nERROR: CABS+ orthogonality check failed, or no CABS vector was retained.")
        print("Try a different --cabs-basis or lower --thresh only if the small eigenvalues are physically meaningful.")
        sys.exit(2)

    print("\nStatus: CABS+ orthogonality check passed.")


if __name__ == "__main__":
    main()
