#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Step 5a: [2]R12 intermediate check for He.

Purpose
-------
This script does NOT compute the final [2]R12 correction.  It reads the
validated Step-4b parent-basis data and constructs/checks the intermediate
objects that are needed before implementing the final contraction.

Input
-----
Default input:

    he_ccpvdz_step4b_obs_fci_rdm.npz

generated by:

    step4b_he_parent_obs_fci_rdm_check.py

Main checks
-----------
1. Re-verify ordinary RDM energy reconstruction in OBS and RI spaces.
2. Define OBS/CABS block indices:
       P = OBS
       Q = CABS/external pair space
3. Build a spin-free generalized Fock matrix in the RI basis:
       F_pq = h_pq + sum_rs D_rs [(pq|rs) - 1/2 (pr|qs)]
   where D is the spin-summed 1-RDM embedded in RI.
4. Build the SP ansatz tensor:
       d[p,q,r,s] = 3/8 delta[p,r]delta[q,s]
                  + 1/8 delta[p,s]delta[q,r]
5. Build diagnostic first-order pair amplitudes:
       A_raw[a,b] = sum_pq f12_ri[a,b,p,q] C[p,q]
       A_sp [a,b] = sum_rs f12_ri[a,b,r,s] C_sp[r,s]
   with
       C_sp[r,s] = sum_pq d[p,q,r,s] C[p,q]
   Then apply a Q-pair mask that removes the pure OBS-OBS block.
6. Report norms by pair block:
       PP, PC, CP, CC
7. Compute reference expectation values of available F12 intermediates:
       <f12>, <f12^2>, <f12 g12>, <[f12,[T,f12]]>
   using the validated spin-free 2-RDM.
8. Optionally build the ordered alpha-beta pair Hamiltonian in the RI basis
   and report naive Hylleraas-like diagnostics. These are for debugging only,
   not the final [2]R12 correction.

Important
---------
The current corr factor in Step 4b is a one-Gaussian testing factor, not the
full fitted Slater expansion used in the article.  Therefore all numerical
R12-like quantities in this script are diagnostic only.

Usage
-----
    python step5a_he_r12_intermediate_check.py

Optional:
    python step5a_he_r12_intermediate_check.py --inp he_ccpvdz_step4b_obs_fci_rdm.npz
    python step5a_he_r12_intermediate_check.py --skip-pair-hamiltonian
"""

from __future__ import annotations

import argparse
import json
import sys
from typing import Dict, Any, Tuple

import numpy as np


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--inp", default="he_ccpvdz_step4b_obs_fci_rdm.npz", help="Step-4b npz input.")
    p.add_argument("--out", default=None, help="Output npz file.")
    p.add_argument("--summary", default=None, help="Summary txt/json file.")
    p.add_argument("--skip-pair-hamiltonian", action="store_true", help="Skip pair-Hamiltonian diagnostics.")
    p.add_argument("--max-pair-dim", type=int, default=2500, help="Skip pair Hamiltonian if nri^2 exceeds this.")
    return p.parse_args()


def maxabs(A: np.ndarray) -> float:
    return float(np.max(np.abs(A))) if A.size else 0.0


def sym(A: np.ndarray) -> np.ndarray:
    return 0.5 * (A + A.T)


def load_metadata(data) -> Dict[str, Any]:
    if "metadata_json" not in data:
        return {}
    try:
        return json.loads(str(data["metadata_json"]))
    except Exception:
        return {}


def reconstruct_energy(h: np.ndarray, eri: np.ndarray, dm1: np.ndarray, dm2: np.ndarray, enuc: float = 0.0):
    e1 = float(np.einsum("pq,pq", h, dm1, optimize=True))
    e2 = float(0.5 * np.einsum("pqrs,pqrs", eri, dm2, optimize=True))
    return e1 + e2 + enuc, e1, e2


def two_body_expectation(T: np.ndarray, dm2: np.ndarray) -> float:
    """Return 1/2 sum_pqrs T[p,q,r,s] dm2[p,q,r,s]."""
    return float(0.5 * np.einsum("pqrs,pqrs", T, dm2, optimize=True))


def tensor_diag(T: np.ndarray) -> Dict[str, Any]:
    return {
        "shape": list(T.shape),
        "has_nan": bool(np.isnan(T).any()),
        "has_inf": bool(np.isinf(T).any()),
        "norm": float(np.linalg.norm(T.reshape(-1))) if T.size else 0.0,
        "max_abs": float(np.max(np.abs(T))) if T.size else 0.0,
        "bra_ket_error": maxabs(T - T.transpose(2, 3, 0, 1)),
        "pair_bra_error": maxabs(T - T.transpose(1, 0, 2, 3)),
        "pair_ket_error": maxabs(T - T.transpose(0, 1, 3, 2)),
    }


def rdm_diag(dm1: np.ndarray, dm2: np.ndarray) -> Dict[str, Any]:
    occ = np.linalg.eigvalsh(sym(dm1))[::-1]
    return {
        "trace_dm1": float(np.trace(dm1)),
        "trace_dm2": float(np.einsum("pprr->", dm2, optimize=True)),
        "max_dm1_asym": maxabs(dm1 - dm1.T),
        "max_dm2_bra_ket_error": maxabs(dm2 - dm2.transpose(2, 3, 0, 1)),
        "natural_occupations": occ.tolist(),
    }


def build_generalized_fock_spinfree(h: np.ndarray, eri: np.ndarray, dm1: np.ndarray) -> np.ndarray:
    """
    Spin-free closed-shell-like generalized Fock matrix.

    eri[p,q,r,s] = (pq|rs).

    F[p,q] = h[p,q] + sum_rs D[r,s] * [(pq|rs) - 1/2 (pr|qs)]

    This is the convention used here for diagnostics.  It is not yet asserted
    as the final [2]R12 paper convention.
    """
    J = np.einsum("rs,pqrs->pq", dm1, eri, optimize=True)
    K = np.einsum("rs,prqs->pq", dm1, eri, optimize=True)
    F = h + J - 0.5 * K
    return sym(F)


def block_matrix_norms(M: np.ndarray, nobs: int) -> Dict[str, float]:
    P = slice(0, nobs)
    C = slice(nobs, M.shape[0])
    return {
        "PP": float(np.linalg.norm(M[P, P])),
        "PC": float(np.linalg.norm(M[P, C])),
        "CP": float(np.linalg.norm(M[C, P])),
        "CC": float(np.linalg.norm(M[C, C])),
        "total": float(np.linalg.norm(M)),
    }


def build_sp_tensor(nobs: int) -> np.ndarray:
    """
    d[p,q,r,s] = 3/8 delta[p,r]delta[q,s] + 1/8 delta[p,s]delta[q,r]
    """
    D = np.zeros((nobs, nobs, nobs, nobs), dtype=float)
    for p in range(nobs):
        for q in range(nobs):
            D[p, q, p, q] += 3.0 / 8.0
            D[p, q, q, p] += 1.0 / 8.0
    return D


def sp_tensor_diag(D: np.ndarray) -> Dict[str, float]:
    return {
        "shape0": int(D.shape[0]),
        "norm": float(np.linalg.norm(D.reshape(-1))),
        "max_abs": float(np.max(np.abs(D))) if D.size else 0.0,
        "pq_sym_error": maxabs(D - D.transpose(1, 0, 2, 3)),
        "rs_sym_error": maxabs(D - D.transpose(0, 1, 3, 2)),
        "bra_ket_error": maxabs(D - D.transpose(2, 3, 0, 1)),
    }


def pair_block_masks(nri: int, nobs: int) -> Dict[str, np.ndarray]:
    idx = np.arange(nri)
    p = idx < nobs
    P1, P2 = np.meshgrid(p, p, indexing="ij")
    pp = P1 & P2
    pc = P1 & (~P2)
    cp = (~P1) & P2
    cc = (~P1) & (~P2)
    qpair = ~pp
    return {"PP": pp, "PC": pc, "CP": cp, "CC": cc, "Q": qpair}


def pair_amp_block_norms(A: np.ndarray, nobs: int) -> Dict[str, float]:
    masks = pair_block_masks(A.shape[0], nobs)
    out = {}
    for key in ["PP", "PC", "CP", "CC", "Q"]:
        out[key] = float(np.linalg.norm(A[masks[key]]))
    out["total"] = float(np.linalg.norm(A))
    return out


def apply_q_pair(A: np.ndarray, nobs: int) -> np.ndarray:
    out = np.array(A, dtype=float, copy=True)
    out[:nobs, :nobs] = 0.0
    return out


def build_pair_hamiltonian(h: np.ndarray, eri: np.ndarray) -> np.ndarray:
    """
    Ordered alpha-beta pair basis |p alpha, q beta>.

    <p_a q_b | H | r_a s_b>
      = h[p,r] delta[q,s] + h[q,s] delta[p,r] + (p r | q s)
    """
    n = h.shape[0]
    H = np.zeros((n * n, n * n), dtype=float)
    for p in range(n):
        for q in range(n):
            I = p * n + q
            for r in range(n):
                for s in range(n):
                    J = r * n + s
                    val = 0.0
                    if q == s:
                        val += h[p, r]
                    if p == r:
                        val += h[q, s]
                    val += eri[p, r, q, s]
                    H[I, J] = val
    return sym(H)


def pair_hylleraas_diagnostic(H: np.ndarray, psi0: np.ndarray, A: np.ndarray, E_ref_elec: float) -> Dict[str, float]:
    """
    Naive pair-space diagnostics.  Not the final [2]R12 contraction.

    psi0 and A are matrix-shaped pair amplitudes.  Both are flattened in the
    same ordered alpha-beta pair basis.
    """
    v0 = psi0.reshape(-1)
    a = A.reshape(-1)
    H0 = H - E_ref_elec * np.eye(H.shape[0])

    norm_v0 = float(np.linalg.norm(v0))
    norm_a = float(np.linalg.norm(a))
    e_v0 = float(v0 @ H @ v0)
    residual = float(np.linalg.norm(H0 @ v0))
    coupling = float(v0 @ H @ a)
    quadratic = float(a @ H0 @ a)
    j2_naive = quadratic + 2.0 * coupling

    return {
        "norm_psi0": norm_v0,
        "norm_A": norm_a,
        "E_pair_expectation_psi0_elec": e_v0,
        "residual_norm_HminusE_on_psi0": residual,
        "coupling_psi0_H_A": coupling,
        "quadratic_A_HminusE_A": quadratic,
        "J2_naive_diagnostic": j2_naive,
    }


def main():
    args = parse_args()

    if args.out is None:
        args.out = "he_ccpvdz_step5a_r12_intermediates.npz"
    if args.summary is None:
        args.summary = "he_ccpvdz_step5a_r12_intermediates_summary.txt"

    print("=" * 80)
    print("Step 5a | R12 intermediate check | He")
    print("=" * 80)
    print(f"input = {args.inp}")

    data = np.load(args.inp, allow_pickle=True)
    meta = load_metadata(data)

    required = [
        "h_obs", "eri_obs", "dm1_obs", "dm2_obs",
        "h_ri", "eri_ri", "f12_ri", "f12sq_ri", "f12g12_ri", "f12dc_ri",
        "dm1_ri", "dm2_ri", "pair_coeff_ab_obs",
        "E_obs_fci", "Enuc",
    ]
    missing = [k for k in required if k not in data]
    if missing:
        raise RuntimeError(f"Missing required arrays in {args.inp}: {missing}")

    h_obs = np.array(data["h_obs"], dtype=float)
    eri_obs = np.array(data["eri_obs"], dtype=float)
    dm1_obs = np.array(data["dm1_obs"], dtype=float)
    dm2_obs = np.array(data["dm2_obs"], dtype=float)

    h_ri = np.array(data["h_ri"], dtype=float)
    eri_ri = np.array(data["eri_ri"], dtype=float)
    f12_ri = np.array(data["f12_ri"], dtype=float)
    f12sq_ri = np.array(data["f12sq_ri"], dtype=float)
    f12g12_ri = np.array(data["f12g12_ri"], dtype=float)
    f12dc_ri = np.array(data["f12dc_ri"], dtype=float)
    dm1_ri = np.array(data["dm1_ri"], dtype=float)
    dm2_ri = np.array(data["dm2_ri"], dtype=float)
    Cab_obs = np.array(data["pair_coeff_ab_obs"], dtype=float)

    E_obs_fci = float(np.array(data["E_obs_fci"]))
    enuc = float(np.array(data["Enuc"]))
    E_ref_elec = E_obs_fci - enuc

    nobs = h_obs.shape[0]
    nri = h_ri.shape[0]
    ncabs = nri - nobs

    print(f"nobs = {nobs}, ncabs = {ncabs}, nri = {nri}")

    # Energy checks.
    E_obs_rdm, E1_obs, E2_obs = reconstruct_energy(h_obs, eri_obs, dm1_obs, dm2_obs, enuc=enuc)
    E_ri_rdm, E1_ri, E2_ri = reconstruct_energy(h_ri, eri_ri, dm1_ri, dm2_ri, enuc=enuc)

    # RDM diagnostics.
    obs_rdm_diag = rdm_diag(dm1_obs, dm2_obs)
    ri_rdm_diag = rdm_diag(dm1_ri, dm2_ri)

    print("\n[Energy reconstruction]")
    print(f"E_obs_fci              = {E_obs_fci: .14f} Eh")
    print(f"E_obs_rdm              = {E_obs_rdm: .14f} Eh")
    print(f"E_ri_embedded_rdm      = {E_ri_rdm: .14f} Eh")
    print(f"Delta obs-rdm - fci    = {E_obs_rdm - E_obs_fci: .3e} Eh")
    print(f"Delta ri-rdm - fci     = {E_ri_rdm - E_obs_fci: .3e} Eh")
    print(f"E1_obs, E2_obs         = {E1_obs: .14f}, {E2_obs: .14f} Eh")

    print("\n[RDM traces]")
    print(f"Tr dm1_obs = {obs_rdm_diag['trace_dm1']:.12f}")
    print(f"Tr dm2_obs = {obs_rdm_diag['trace_dm2']:.12f}")
    print(f"Tr dm1_ri  = {ri_rdm_diag['trace_dm1']:.12f}")
    print(f"Tr dm2_ri  = {ri_rdm_diag['trace_dm2']:.12f}")

    # Generalized Fock.
    F_ri = build_generalized_fock_spinfree(h_ri, eri_ri, dm1_ri)
    fock_diag = {
        "shape": list(F_ri.shape),
        "hermiticity_error": maxabs(F_ri - F_ri.T),
        "norm": float(np.linalg.norm(F_ri)),
        "max_abs": float(np.max(np.abs(F_ri))) if F_ri.size else 0.0,
        "block_norms": block_matrix_norms(F_ri, nobs),
        "eigenvalues": np.linalg.eigvalsh(F_ri).tolist(),
    }

    print("\n[Generalized Fock diagnostic]")
    print(f"Max|F-F.T|             = {fock_diag['hermiticity_error']:.3e}")
    print(f"||F||                  = {fock_diag['norm']:.6e}")
    print(f"block norms            = {fock_diag['block_norms']}")

    # SP ansatz tensor and SP-transformed pair coefficient.
    D_sp = build_sp_tensor(nobs)
    D_sp_diag = sp_tensor_diag(D_sp)
    Cab_sp = np.einsum("pqrs,pq->rs", D_sp, Cab_obs, optimize=True)

    # Diagnostic first-order amplitudes in RI pair representation.
    # Raw: F12 acting directly on the OBS pair coefficient.
    A_raw = np.einsum("abpq,pq->ab", f12_ri[:, :, :nobs, :nobs], Cab_obs, optimize=True)
    A_sp = np.einsum("abrs,rs->ab", f12_ri[:, :, :nobs, :nobs], Cab_sp, optimize=True)

    A_raw_Q = apply_q_pair(A_raw, nobs)
    A_sp_Q = apply_q_pair(A_sp, nobs)

    amp_diag = {
        "Cab_obs_norm": float(np.linalg.norm(Cab_obs)),
        "Cab_obs_symmetry_error": maxabs(Cab_obs - Cab_obs.T),
        "Cab_sp_norm": float(np.linalg.norm(Cab_sp)),
        "Cab_sp_symmetry_error": maxabs(Cab_sp - Cab_sp.T),
        "A_raw_block_norms": pair_amp_block_norms(A_raw, nobs),
        "A_raw_Q_block_norms": pair_amp_block_norms(A_raw_Q, nobs),
        "A_sp_block_norms": pair_amp_block_norms(A_sp, nobs),
        "A_sp_Q_block_norms": pair_amp_block_norms(A_sp_Q, nobs),
        "A_raw_Q_has_nan": bool(np.isnan(A_raw_Q).any()),
        "A_sp_Q_has_nan": bool(np.isnan(A_sp_Q).any()),
    }

    print("\n[SP ansatz and F12 pair-amplitude diagnostics]")
    print(f"D_sp norm              = {D_sp_diag['norm']:.6e}")
    print(f"D_sp bra-ket error     = {D_sp_diag['bra_ket_error']:.3e}")
    print(f"||Cab_obs||            = {amp_diag['Cab_obs_norm']:.12f}")
    print(f"||Cab_sp||             = {amp_diag['Cab_sp_norm']:.12f}")
    print(f"A_raw block norms      = {amp_diag['A_raw_block_norms']}")
    print(f"A_raw_Q block norms    = {amp_diag['A_raw_Q_block_norms']}")
    print(f"A_sp block norms       = {amp_diag['A_sp_block_norms']}")
    print(f"A_sp_Q block norms     = {amp_diag['A_sp_Q_block_norms']}")

    # F12 expectation values using RI-embedded RDM.
    f12_expect = {
        "eri": two_body_expectation(eri_ri, dm2_ri),
        "f12": two_body_expectation(f12_ri, dm2_ri),
        "f12sq": two_body_expectation(f12sq_ri, dm2_ri),
        "f12g12": two_body_expectation(f12g12_ri, dm2_ri),
        "f12dc": two_body_expectation(f12dc_ri, dm2_ri),
    }

    print("\n[Reference two-body expectation values]")
    for k, v in f12_expect.items():
        print(f"<{k}> = {v: .14e}")

    tensor_diags = {
        "eri_ri": tensor_diag(eri_ri),
        "f12_ri": tensor_diag(f12_ri),
        "f12sq_ri": tensor_diag(f12sq_ri),
        "f12g12_ri": tensor_diag(f12g12_ri),
        "f12dc_ri": tensor_diag(f12dc_ri),
    }

    # Naive pair-Hamiltonian diagnostics, for debugging only.
    pair_diag = {}
    if not args.skip_pair_hamiltonian and nri * nri <= args.max_pair_dim:
        print("\n[Naive pair-space diagnostics: debugging only]")
        H_pair = build_pair_hamiltonian(h_ri, eri_ri)

        psi0_ri = np.zeros((nri, nri), dtype=float)
        psi0_ri[:nobs, :nobs] = Cab_obs

        pair_diag["psi0"] = pair_hylleraas_diagnostic(H_pair, psi0_ri, psi0_ri, E_ref_elec)
        pair_diag["A_raw_Q"] = pair_hylleraas_diagnostic(H_pair, psi0_ri, A_raw_Q, E_ref_elec)
        pair_diag["A_sp_Q"] = pair_hylleraas_diagnostic(H_pair, psi0_ri, A_sp_Q, E_ref_elec)

        print(f"pair dim               = {H_pair.shape[0]}")
        print(f"E_pair(psi0) elec      = {pair_diag['psi0']['E_pair_expectation_psi0_elec']: .14f} Eh")
        print(f"residual ||(H-E)psi0|| = {pair_diag['psi0']['residual_norm_HminusE_on_psi0']:.6e}")
        print(f"A_raw_Q norm           = {pair_diag['A_raw_Q']['norm_A']:.6e}")
        print(f"A_raw_Q coupling       = {pair_diag['A_raw_Q']['coupling_psi0_H_A']: .6e}")
        print(f"A_raw_Q J2 naive       = {pair_diag['A_raw_Q']['J2_naive_diagnostic']: .6e}")
        print(f"A_sp_Q norm            = {pair_diag['A_sp_Q']['norm_A']:.6e}")
        print(f"A_sp_Q coupling        = {pair_diag['A_sp_Q']['coupling_psi0_H_A']: .6e}")
        print(f"A_sp_Q J2 naive        = {pair_diag['A_sp_Q']['J2_naive_diagnostic']: .6e}")
    else:
        pair_diag["skipped"] = True
        pair_diag["reason"] = "requested skip or pair dimension too large"

    metadata = {
        "source_file": args.inp,
        "step4b_metadata": meta,
        "nobs": int(nobs),
        "ncabs": int(ncabs),
        "nri": int(nri),
        "enuc": float(enuc),
        "E_obs_fci": float(E_obs_fci),
        "E_ref_elec": float(E_ref_elec),
        "E_obs_rdm": float(E_obs_rdm),
        "E_ri_embedded_rdm": float(E_ri_rdm),
        "delta_obs_rdm_minus_fci": float(E_obs_rdm - E_obs_fci),
        "delta_ri_rdm_minus_fci": float(E_ri_rdm - E_obs_fci),
        "E1_obs": float(E1_obs),
        "E2_obs": float(E2_obs),
        "E1_ri": float(E1_ri),
        "E2_ri": float(E2_ri),
        "obs_rdm_diag": obs_rdm_diag,
        "ri_rdm_diag": ri_rdm_diag,
        "fock_diag": fock_diag,
        "sp_tensor_diag": D_sp_diag,
        "amplitude_diag": amp_diag,
        "f12_expectations": f12_expect,
        "tensor_diags": tensor_diags,
        "pair_space_diagnostics": pair_diag,
        "note": (
            "This file contains diagnostic R12 intermediates only. "
            "The current corr factor is a testing Gaussian unless the Step-4b input used a fitted expansion."
        ),
    }

    np.savez(
        args.out,
        F_ri=F_ri,
        D_sp=D_sp,
        Cab_obs=Cab_obs,
        Cab_sp=Cab_sp,
        A_raw=A_raw,
        A_raw_Q=A_raw_Q,
        A_sp=A_sp,
        A_sp_Q=A_sp_Q,
        h_ri=h_ri,
        eri_ri=eri_ri,
        f12_ri=f12_ri,
        f12sq_ri=f12sq_ri,
        f12g12_ri=f12g12_ri,
        f12dc_ri=f12dc_ri,
        dm1_obs=dm1_obs,
        dm2_obs=dm2_obs,
        dm1_ri=dm1_ri,
        dm2_ri=dm2_ri,
        metadata_json=np.array(json.dumps(metadata, indent=2)),
    )

    with open(args.summary, "w", encoding="utf-8") as f:
        f.write(json.dumps(metadata, indent=2))
        f.write("\n")

    print("\n[Saved]")
    print(" ", args.out)
    print(" ", args.summary)

    ok = (
        abs(E_obs_rdm - E_obs_fci) < 1e-10
        and abs(E_ri_rdm - E_obs_fci) < 1e-10
        and abs(obs_rdm_diag["trace_dm1"] - 2.0) < 1e-10
        and abs(obs_rdm_diag["trace_dm2"] - 2.0) < 1e-10
        and fock_diag["hermiticity_error"] < 1e-10
        and not amp_diag["A_raw_Q_has_nan"]
        and not amp_diag["A_sp_Q_has_nan"]
        and all(not d["has_nan"] and not d["has_inf"] for d in tensor_diags.values())
    )

    if not ok:
        print("\nERROR: Step 5a intermediate check failed.")
        print("Inspect energy reconstruction, RDM traces, Fock hermiticity, or NaN diagnostics.")
        sys.exit(2)

    print("\nStatus: Step 5a R12 intermediate check passed.")


if __name__ == "__main__":
    main()
