#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Step 7c: Build a Step-4b-like ECG-NO bridge file and check energy.

Default selection is the small 12-qubit ECG-NO bridge test:

    channels = s,p
    picks    = s[0,1,2], p[0]

This gives 6 spatial OBS orbitals.  The selected ECG-NO C_obs is reused in the
same PySCF/Psi4 AO order audited by Step 7b.  RDMs are generated by exact
two-electron alpha-beta FCI in this selected OBS space, then embedded in RI for
the Step-4b-style energy reconstruction check.
"""

from __future__ import annotations

import argparse
import json
import sys
from types import SimpleNamespace
from typing import Any, Dict, List, Tuple

import numpy as np

from r12_common import (
    assert_finite,
    embed_rdm_to_ri,
    maxabs,
    rdm_diagnostics,
    reconstruct_energy,
    tensor_diagnostics,
)
from step4b_he_parent_obs_fci_rdm_check import (
    asarray_psi4,
    compute_parent_integrals,
    construct_parent_cabs_plus,
    parse_corr,
    rdms_from_ab_pair,
    solve_two_electron_ab_fci,
    transform_1index,
    transform_4index,
)
from step6a_fit_slater_corr import fit_gaussian_expansion
from step7b_export_ecg_no_orbitals import (
    GTO_PARAMS,
    L_INFO,
    build_ao_index,
    build_ecg_no_cobs,
    build_pyscf_mol,
    even_tempered_exponents,
    load_no_mats,
    parse_int_list,
    psi4_basis_string,
)


def parse_args():
    p = argparse.ArgumentParser()
    p.add_argument("--no-dir", default="local_external/he-sin")
    p.add_argument("--channels", default="s,p")
    p.add_argument("--s-pick", default="0,1,2")
    p.add_argument("--p-pick", default="0")
    p.add_argument("--d-pick", default="")
    p.add_argument("--f-pick", default="")
    p.add_argument("--basis-name", default="heecgnosp")
    p.add_argument("--gamma", type=float, default=1.4)
    p.add_argument("--fitN", type=int, default=7)
    p.add_argument("--corr", default=None, help="Manual corr list: 'exponent,coefficient;...'. Overrides --fitN.")
    p.add_argument("--thresh", type=float, default=1e-10)
    p.add_argument("--memory", default="4 GB")
    p.add_argument("--nthreads", type=int, default=1)
    p.add_argument("--psi4-output", default=None)
    p.add_argument("--out", default=None)
    p.add_argument("--summary", default=None)
    p.add_argument("--json", default=None)
    p.add_argument("--energy-tol", type=float, default=1e-9)
    p.add_argument("--orth-tol", type=float, default=1e-8)
    p.add_argument("--save-compressed", action="store_true", help="Use np.savez_compressed. Smaller but slower.")
    return p.parse_args()


def safe_tag(channels: List[str], picks: Dict[str, List[int]], fitn: int | None) -> str:
    parts = ["".join(channels)]
    for ch in channels:
        parts.append(f"{ch}{''.join(str(i) for i in picks[ch])}")
    if fitn is not None:
        parts.append(f"fitN{fitn}")
    return "_".join(parts)


def get_corr(args) -> Tuple[List[Tuple[float, float]], Dict[str, Any]]:
    if args.corr is not None:
        corr = parse_corr(args.corr)
        return corr, {
            "source": "manual --corr",
            "corr_string": args.corr,
            "corr": [[float(a), float(c)] for a, c in corr],
        }

    fit_args = SimpleNamespace(
        gamma=args.gamma,
        nterms=args.fitN,
        alpha_min=0.08,
        alpha_max=60.0,
        rmin=0.0,
        rmax=8.0,
        ngrid=2000,
        grid="quadratic",
        weight="short",
        ridge=0.0,
        nonpositive_coeff=False,
    )
    fit = fit_gaussian_expansion(fit_args)
    corr = [(float(a), float(c)) for a, c in fit["corr"]]
    return corr, {
        "source": "step6a local least-squares fitted Slater Gaussian expansion",
        "fitN": int(args.fitN),
        "gamma": float(args.gamma),
        "corr_string": fit["corr_string"],
        "corr": [[float(a), float(c)] for a, c in corr],
        "fit_metrics": fit["metrics"],
        "cusp_note": "Finite Gaussian expansions have f'(0)=0 and cannot exactly reproduce the Slater cusp derivative.",
    }


def build_psi4_parent(name: str, basis_text: str, memory: str, nthreads: int, output_file: str):
    try:
        import psi4
    except Exception as exc:
        raise RuntimeError("Cannot import psi4. Activate the Psi4 environment first.") from exc

    psi4.core.clean()
    psi4.set_memory(memory)
    psi4.set_num_threads(nthreads)
    psi4.core.set_output_file(output_file, False)
    mol = psi4.geometry(
        """
        0 1
        He 0.0 0.0 0.0
        symmetry c1
        units bohr
        """
    )
    psi4.basis_helper(basis_text, name=name, set_option=True)
    psi4.set_options({"basis": name, "reference": "rhf", "scf_type": "pk"})
    wfn = psi4.core.Wavefunction.build(mol, psi4.core.get_global_option("BASIS"))
    mints = psi4.core.MintsHelper(wfn.basisset())
    return mol, wfn, mints


def check_finite_many(arrays: Dict[str, np.ndarray]) -> None:
    for name, arr in arrays.items():
        assert_finite(name, np.asarray(arr))


def symmetrize_bra_ket(T: np.ndarray) -> np.ndarray:
    """Remove tiny numerical bra-ket noise from transformed four-index tensors."""
    return 0.5 * (T + T.transpose(2, 3, 0, 1))


def main():
    args = parse_args()
    channels = [x.strip() for x in args.channels.split(",") if x.strip()]
    for ch in channels:
        if ch not in L_INFO:
            raise ValueError(f"Unknown channel {ch}")

    picks = {
        "s": parse_int_list(args.s_pick),
        "p": parse_int_list(args.p_pick),
        "d": parse_int_list(args.d_pick),
        "f": parse_int_list(args.f_pick),
    }
    for ch, vals in picks.items():
        if vals and ch not in channels:
            raise ValueError(f"{ch}_pick={vals} but channel {ch} is not included")

    tag = safe_tag(channels, picks, None if args.corr else args.fitN)
    args.psi4_output = args.psi4_output or f"psi4_step7c_ecg_no_{tag}.out"
    args.out = args.out or f"step7c_ecg_no_{tag}_step4b_like.npz"
    args.summary = args.summary or f"step7c_ecg_no_{tag}_step4b_like_summary.txt"
    args.json = args.json or f"step7c_ecg_no_{tag}_step4b_like.json"

    ns, mats = load_no_mats(args.no_dir)
    exponents = {ch: even_tempered_exponents(*GTO_PARAMS[ch], ns) for ch in L_INFO}
    mol_pyscf = build_pyscf_mol(ns, channels, exponents)
    S_pyscf = mol_pyscf.intor("int1e_ovlp")
    ao_index = build_ao_index(ns, channels)
    C_obs, labels = build_ecg_no_cobs(mats, ns, mol_pyscf, S_pyscf, ao_index, channels, picks)
    nobs = C_obs.shape[1]

    basis_text = psi4_basis_string(args.basis_name, channels, exponents)
    mol_psi4, wfn, mints = build_psi4_parent(args.basis_name, basis_text, args.memory, args.nthreads, args.psi4_output)
    enuc = float(mol_psi4.nuclear_repulsion_energy())
    nao = int(wfn.basisset().nbf())
    if nao != mol_pyscf.nao:
        raise RuntimeError(f"PySCF/Psi4 AO dimension mismatch: {mol_pyscf.nao} vs {nao}")

    S_psi4 = asarray_psi4(mints.ao_overlap())
    direct_overlap_error = maxabs(S_pyscf - S_psi4)
    cobs_orth_pyscf = maxabs(C_obs.T @ S_pyscf @ C_obs - np.eye(nobs))
    cobs_orth_psi4 = maxabs(C_obs.T @ S_psi4 @ C_obs - np.eye(nobs))
    if direct_overlap_error > 1e-8 or cobs_orth_psi4 > 1e-8:
        raise RuntimeError(
            "PySCF/Psi4 AO order is not directly compatible for this selection. "
            f"Max|S_pyscf-S_psi4|={direct_overlap_error:.3e}, "
            f"Max|C_obs^T S_psi4 C_obs-I|={cobs_orth_psi4:.3e}"
        )

    corr, corr_info = get_corr(args)
    ao = compute_parent_integrals(wfn, mints, corr)
    cabs_info = construct_parent_cabs_plus(C_obs, ao["S"], args.thresh)
    C_cabs = cabs_info["C_cabs"]
    C_ri = cabs_info["C_ri"]
    nri = int(cabs_info["nri"])
    ncabs = int(cabs_info["ncabs"])

    h_obs = transform_1index(ao["h"], C_obs)
    eri_obs = symmetrize_bra_ket(transform_4index(ao["eri"], C_obs))
    E_obs_fci, E_obs_elec, Cab_obs, evals_obs = solve_two_electron_ab_fci(h_obs, eri_obs, enuc=enuc)
    dm1_obs, dm2_obs, dm1a_obs, dm1b_obs = rdms_from_ab_pair(Cab_obs)
    E_obs_rdm, E1_obs, E2_obs = reconstruct_energy(h_obs, eri_obs, dm1_obs, dm2_obs, enuc=enuc)

    h_ri = transform_1index(ao["h"], C_ri)
    eri_ri = symmetrize_bra_ket(transform_4index(ao["eri"], C_ri))
    f12_ri = symmetrize_bra_ket(transform_4index(ao["f12"], C_ri))
    f12sq_ri = symmetrize_bra_ket(transform_4index(ao["f12sq"], C_ri))
    f12g12_ri = symmetrize_bra_ket(transform_4index(ao["f12g12"], C_ri))
    f12dc_ri = symmetrize_bra_ket(transform_4index(ao["f12dc"], C_ri))
    dm1_ri, dm2_ri = embed_rdm_to_ri(dm1_obs, dm2_obs, nri=nri, nobs=nobs)
    E_ri_rdm, E1_ri, E2_ri = reconstruct_energy(h_ri, eri_ri, dm1_ri, dm2_ri, enuc=enuc)

    diag_obs = rdm_diagnostics(dm1_obs, dm2_obs)
    diag_ri = rdm_diagnostics(dm1_ri, dm2_ri)
    tensor_diags = {
        "eri_ri": tensor_diagnostics(eri_ri),
        "f12_ri": tensor_diagnostics(f12_ri),
        "f12sq_ri": tensor_diagnostics(f12sq_ri),
        "f12g12_ri": tensor_diagnostics(f12g12_ri),
        "f12dc_ri": tensor_diagnostics(f12dc_ri),
    }
    check_finite_many(
        {
            "h_obs": h_obs,
            "eri_obs": eri_obs,
            "h_ri": h_ri,
            "eri_ri": eri_ri,
            "f12_ri": f12_ri,
            "f12sq_ri": f12sq_ri,
            "f12g12_ri": f12g12_ri,
            "f12dc_ri": f12dc_ri,
            "dm1_obs": dm1_obs,
            "dm2_obs": dm2_obs,
            "dm1_ri": dm1_ri,
            "dm2_ri": dm2_ri,
        }
    )

    checks = {
        "direct_overlap_error": float(direct_overlap_error),
        "cobs_orth_pyscf": float(cobs_orth_pyscf),
        "cobs_orth_psi4_same_order": float(cobs_orth_psi4),
        "obs_orth_error": float(cabs_info["obs_orth_error"]),
        "cabs_orth_error": float(cabs_info["cabs_orth_error"]),
        "obs_cabs_cross_error": float(cabs_info["obs_cabs_cross_error"]),
        "ri_orth_error": float(cabs_info["ri_orth_error"]),
        "delta_obs_rdm_minus_obs_fci": float(E_obs_rdm - E_obs_fci),
        "delta_ri_rdm_minus_obs_fci": float(E_ri_rdm - E_obs_fci),
        "trace_dm1_error": float(diag_obs["trace_dm1"] - 2.0),
        "trace_dm2_error": float(diag_obs["trace_dm2"] - 2.0),
        "dm2_bra_ket_error": float(diag_obs["max_dm2_bra_ket_error"]),
    }
    failures = []
    for key in ["obs_orth_error", "cabs_orth_error", "obs_cabs_cross_error", "ri_orth_error"]:
        if checks[key] > args.orth_tol:
            failures.append(key)
    if abs(checks["delta_obs_rdm_minus_obs_fci"]) > args.energy_tol:
        failures.append("obs_energy_reconstruction")
    if abs(checks["delta_ri_rdm_minus_obs_fci"]) > args.energy_tol:
        failures.append("ri_energy_reconstruction")
    if abs(checks["trace_dm1_error"]) > 1e-10:
        failures.append("dm1_trace")
    if abs(checks["trace_dm2_error"]) > 1e-10:
        failures.append("dm2_trace")
    if checks["dm2_bra_ket_error"] > 1e-10:
        failures.append("dm2_bra_ket")
    for name, d in tensor_diags.items():
        if d["has_nan"] or d["has_inf"]:
            failures.append(f"{name}_finite")

    metadata = {
        "step": "7c",
        "system": "He",
        "no_dir": str(args.no_dir),
        "channels": channels,
        "picks": picks,
        "small_space_note": "Default s[0,1,2]+p[0] gives 6 spatial orbitals = 12 qubits.",
        "basis_name": args.basis_name,
        "basis_text": basis_text,
        "ns": int(ns),
        "nao": int(nao),
        "nobs": int(nobs),
        "ncabs": int(ncabs),
        "nri": int(nri),
        "labels": labels,
        "enuc": float(enuc),
        "corr_info": corr_info,
        "rdm_source": "two-electron alpha-beta FCI in the selected ECG-NO OBS space",
        "energies": {
            "E_obs_fci": float(E_obs_fci),
            "E_obs_elec": float(E_obs_elec),
            "E_obs_rdm": float(E_obs_rdm),
            "E_ri_embedded_rdm": float(E_ri_rdm),
            "E1_obs": float(E1_obs),
            "E2_obs": float(E2_obs),
            "E1_ri": float(E1_ri),
            "E2_ri": float(E2_ri),
        },
        "checks": checks,
        "passed": not failures,
        "failures": failures,
        "rdm_obs_diag": diag_obs,
        "rdm_ri_diag": diag_ri,
        "cabs_info": {
            k: v for k, v in cabs_info.items()
            if k not in ["C_cabs", "C_ri", "projected_cabs_overlap_evals", "keep"]
        },
        "ri_tensor_diags": tensor_diags,
    }

    save_dict = {
        "S_ao": ao["S"],
        "h_ao": ao["h"],
        "C_obs": C_obs,
        "C_obs_psi4_same_order": C_obs,
        "C_cabs": C_cabs,
        "C_ri": C_ri,
        "h_obs": h_obs,
        "eri_obs": eri_obs,
        "h_ri": h_ri,
        "eri_ri": eri_ri,
        "f12_ri": f12_ri,
        "f12sq_ri": f12sq_ri,
        "f12g12_ri": f12g12_ri,
        "f12dc_ri": f12dc_ri,
        "dm1_obs": dm1_obs,
        "dm2_obs": dm2_obs,
        "dm1_alpha_obs": dm1a_obs,
        "dm1_beta_obs": dm1b_obs,
        "dm1_ri": dm1_ri,
        "dm2_ri": dm2_ri,
        "pair_coeff_ab_obs": Cab_obs,
        "obs_fci_eigenvalues": evals_obs,
        "projected_cabs_overlap_evals": cabs_info["projected_cabs_overlap_evals"],
        "keep": cabs_info["keep"],
        "labels": np.array(labels, dtype=object),
        "channels": np.array(channels, dtype=object),
        "basis_text": np.array(basis_text),
        "E_obs_fci": np.array(E_obs_fci),
        "E_obs_rdm": np.array(E_obs_rdm),
        "E_ri_embedded_rdm": np.array(E_ri_rdm),
        "Enuc": np.array(enuc),
        "metadata_json": np.array(json.dumps(metadata, indent=2)),
    }
    save_func = np.savez_compressed if args.save_compressed else np.savez
    save_func(args.out, **save_dict)
    with open(args.json, "w", encoding="utf-8") as f:
        json.dump(metadata, f, indent=2)

    lines = []
    lines.append("=" * 96)
    lines.append("Step 7c | ECG-NO selected-OBS Step-4b-like bridge | He")
    lines.append("=" * 96)
    lines.append(f"no_dir       = {args.no_dir}")
    lines.append(f"channels     = {channels}")
    lines.append(f"picks        = {picks}")
    lines.append(f"ns / nao     = {ns} / {nao}")
    lines.append(f"nobs/ncabs/nri = {nobs}/{ncabs}/{nri}  ({2 * nobs} qubits)")
    lines.append(f"corr source  = {corr_info['source']}")
    lines.append("")
    lines.append("[AO / C_obs audit]")
    lines.append(f"Max|S_pyscf-S_psi4|              = {direct_overlap_error:.3e}")
    lines.append(f"Max|C_obs^T S_pyscf C_obs-I|    = {cobs_orth_pyscf:.3e}")
    lines.append(f"Max|C_obs^T S_psi4 C_obs-I|     = {cobs_orth_psi4:.3e}")
    lines.append(f"labels                          = {labels}")
    lines.append("")
    lines.append("[CABS+]")
    lines.append(f"Max|C_obs^T S C_obs-I|          = {cabs_info['obs_orth_error']:.3e}")
    lines.append(f"Max|C_cabs^T S C_cabs-I|        = {cabs_info['cabs_orth_error']:.3e}")
    lines.append(f"Max|C_obs^T S C_cabs|           = {cabs_info['obs_cabs_cross_error']:.3e}")
    lines.append(f"Max|C_ri^T S C_ri-I|            = {cabs_info['ri_orth_error']:.3e}")
    lines.append("")
    lines.append("[Energy reconstruction]")
    lines.append(f"E_OBS_FCI                        = {E_obs_fci: .14f} Eh")
    lines.append(f"E_OBS_RDM                        = {E_obs_rdm: .14f} Eh")
    lines.append(f"E_RI_embedded_RDM                = {E_ri_rdm: .14f} Eh")
    lines.append(f"Delta(OBS_RDM-OBS_FCI)           = {E_obs_rdm - E_obs_fci: .3e} Eh")
    lines.append(f"Delta(RI_RDM-OBS_FCI)            = {E_ri_rdm - E_obs_fci: .3e} Eh")
    lines.append(f"E1_obs / E2_obs                  = {E1_obs: .14f} / {E2_obs: .14f} Eh")
    lines.append("")
    lines.append("[RDM]")
    lines.append(f"Tr(dm1_obs)                      = {diag_obs['trace_dm1']:.12f}")
    lines.append(f"Tr(dm2_obs)                      = {diag_obs['trace_dm2']:.12f}")
    lines.append(f"dm2 bra-ket error                = {diag_obs['max_dm2_bra_ket_error']:.3e}")
    lines.append("Natural occupations              = " + np.array2string(np.array(diag_obs["natural_occupations"]), precision=10))
    lines.append("")
    lines.append("[RI tensor finite/symmetry]")
    for name, d in tensor_diags.items():
        lines.append(f"{name:<10s} shape={d['shape']} nan={d['has_nan']} inf={d['has_inf']} bra-ket={d['bra_ket_error']:.3e}")
    lines.append("")
    lines.append(f"passed                           = {metadata['passed']}")
    if failures:
        lines.append(f"failures                         = {failures}")
    lines.append("")
    lines.append("[Saved]")
    lines.append(f"  {args.out}")
    lines.append(f"  {args.json}")
    lines.append(f"  {args.summary}")

    with open(args.summary, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))
        f.write("\n")
    print("\n".join(lines))

    if failures:
        sys.exit(2)


if __name__ == "__main__":
    main()
